name: Main

on:
  push:
    branches: [main]

jobs:
  deploy-tst:
    runs-on: ubuntu-latest
    environment: tst
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.9.0
      - name: Deploy bundle (tst)
        run: databricks bundle deploy --target tst

  deploy-prd:
    needs: deploy-tst
    runs-on: ubuntu-latest
    environment: prd
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.9.0
      - name: Deploy bundle (prd)
        run: databricks bundle deploy --target prd
